### ISSUE TITLE
CCI used version?

### ISSUE THREAD

**Issue by ghost** [zonnonproject/compiler#2]
I have seen that if i want compile this project from scratch i need compile Spec# but instructions are only for Windows then, i need know wich CC version you used to this project.

**Comment by rmitin** [comment]
If you just want to compile Zonnon compiler, you do not need to dig into Spec# source code. All you need from CCI used in Spec# is already checked in right here together with the Zonnon compiler https://github.com/zonnonproject/compiler/tree/master/solution/CCI/Mono - compiled to work with Mono. You have them also compiled for Windows https://github.com/zonnonproject/compiler/tree/master/solution/CCI/Windows 
They are sufficient to compile Zonnon compiler. Only standard .NET libraries are needed in addition to those three. Difference between Windows and Mono versions of these libraries are minimal. Simply some things that didn't work on Mono in 2010 are commented out.

Only if you want to see source code for those System.Compiler libraries you can go to Spec# source code
http://specsharp.codeplex.com/SourceControl/latest

For example System.Compiler you can also compile yourself from here http://specsharp.codeplex.com/SourceControl/latest#SpecSharp/System.Compiler/ instead of using DLL that is checked in with Zonnon source code. It might not be 1:1, but the they for sure were the same at some point (ca. 2005). Might be Spec# folks did some tweaks that were not taken over into Zonnon code base.

**Comment by ghost** [comment]
And can you assure me that the current version of Spec # works with Zonnon?

**Comment by rmitin** [comment]
No, I cannot, because I have not tested that. The DLLs that are checked in into Zonnon repository work with Zonnon. Spec# is just the only place I am aware of where the code of those DLLs (in some state) is publicly available. So if someone wants to fix something in say System.Compiler, System.Compiler.Framework or System.Compiler.Runtime then taking their code from Spec# repository would be the place to start.

**Comment by ghost** [comment]
Thank you.
